language: c
script: asdf plugin-test R https://github.com/iroddis/asdf-R.git 'R --version'
before_install:
    - sudo apt-get build-essentials
    - sudo apt-get libcurl3-dev 
    - sudo apt-get libreadline-dev
before_script:
    - git clone https://github.com/asdf-vm/asdf.git
    - . asdf/asdf.sh
os:
  - linux
  - osx
